# Generated by Django 2.2.6 on 2019-11-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='product',
            field=models.CharField(default='', max_length=50, verbose_name='所需产品'),
        ),
    ]
