# Generated by Django 2.2.6 on 2019-11-09 11:05

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('category', models.CharField(choices=[('xw', '新闻'), ('gg', '公告'), ('js', '公司介绍')], max_length=2, verbose_name='分类名称')),
                ('picture', models.ImageField(upload_to='product/%Y/%m', verbose_name='产品宣图')),
                ('abstract', models.TextField(default='', max_length=300, verbose_name='文章摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章内容')),
                ('index', models.IntegerField(default=0, verbose_name='优先级')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('source', models.IntegerField(choices=[(0, '公司动态'), (1, '转载报道')], default=0, verbose_name='文章来源')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加/修改时间')),
            ],
            options={
                'verbose_name': '新闻动态',
                'verbose_name_plural': '新闻动态',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Cominfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='公司名称')),
                ('image', models.ImageField(upload_to='cominfo/%Y/%m', verbose_name='logo')),
                ('address', models.CharField(max_length=150, verbose_name='机构地址')),
                ('phone', models.CharField(max_length=15, verbose_name='公司电话')),
                ('fax', models.CharField(default='', max_length=15, verbose_name='公司传真')),
                ('email', models.CharField(max_length=15, verbose_name='公司邮箱')),
                ('city', models.CharField(max_length=50, verbose_name='所在城市')),
                ('active', models.IntegerField(choices=[(0, '未启用'), (1, '已启用')], default=0, verbose_name='启用状态')),
                ('wxqrcode', models.ImageField(default='', upload_to='cominfo/%Y/%m', verbose_name='微信')),
                ('qywxqrcode', models.ImageField(default='', upload_to='cominfo/%Y/%m', verbose_name='企业微信')),
                ('qqqrcode', models.ImageField(default='', upload_to='cominfo/%Y/%m', verbose_name='QQ')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加/修改时间')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='里程碑事件')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='大事简述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '发展历程',
                'verbose_name_plural': '发展历程',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='来信公司名称')),
                ('linker', models.CharField(blank=True, max_length=12, null=True, verbose_name='联系人')),
                ('phone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('email', models.CharField(max_length=15, verbose_name='联系邮箱')),
                ('province', models.CharField(max_length=50, verbose_name='所在省份')),
                ('city', models.CharField(max_length=50, verbose_name='所在城市')),
                ('content', models.TextField(blank=True, default='', max_length=300, null=True, verbose_name='咨询内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='咨询时间')),
            ],
            options={
                'verbose_name': '咨询信息',
                'verbose_name_plural': '咨询信息',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品名称/型号')),
                ('picture', models.ImageField(upload_to='product/%Y/%m', verbose_name='产品宣图')),
                ('abstract', models.TextField(default='', max_length=300, verbose_name='产品简介')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='产品详情')),
                ('parameter', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='产品参数')),
                ('package', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='包装说明')),
                ('index', models.IntegerField(blank=True, null=True, unique=True, verbose_name='优先级')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加/修改时间')),
            ],
            options={
                'verbose_name': '产品列表',
                'verbose_name_plural': '产品列表',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('index', models.IntegerField(blank=True, null=True, unique=True, verbose_name='优先级')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加/修改时间')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
            },
        ),
        migrations.CreateModel(
            name='SolutionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='方案名称')),
                ('picture', models.ImageField(default='', upload_to='solution/%Y/%m', verbose_name='方案图示')),
                ('abstract', models.TextField(default='', max_length=300, verbose_name='方案简介')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='方案详情')),
                ('index', models.IntegerField(blank=True, null=True, unique=True, verbose_name='优先级')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加/修改时间')),
            ],
            options={
                'verbose_name': '系统方案',
                'verbose_name_plural': '系统方案',
            },
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品手册')),
                ('download', models.FileField(upload_to='service/%Y/%m', verbose_name='资源文件')),
                ('index', models.IntegerField(blank=True, null=True, unique=True, verbose_name='优先级')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加/修改时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product', verbose_name='产品名称/型号')),
            ],
            options={
                'verbose_name': '产品资料',
                'verbose_name_plural': '产品资料',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.ProductType', verbose_name='产品分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.SolutionSystem', verbose_name='适用方案'),
        ),
    ]
