# Generated by Django 2.2.6 on 2019-11-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_message_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所在城市'),
        ),
        migrations.AlterField(
            model_name='message',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所在省份'),
        ),
    ]
